### ISSUE TITLE
We need a synchronized button to reopen the request in the offline queue.

### ISSUE THREAD

**Issue by HuYuee** [jevakallio/redux-offline#408]
hi, We need a synchronized button to reopen the request in the offline queue. Can you provide an example? thx very much

**Comment by sobrinho** [comment]
Why do you need to trigger manually when it will be triggered automatically when you lose and regain the connection?

While the feature itself sounds interesting, it kind of points you to the direction that the `detectNetwork` is not working properly.

If you still need this, you can look at the middleware as the starting point to implement something: https://github.com/redux-offline/redux-offline/blob/2308c02693876d3430d22a283e55ecda8351a96a/src/middleware.js#L38

If anyone have more use-cases for this feature, let me know and we can reopen the issue and discuss about it.
