### ISSUE TITLE
Persist does not accept falsey value

### ISSUE THREAD

**Issue by AnderssonChristian** [jevakallio/redux-offline#433]
### Are you using `offline()` or `createOffline()` API?
offline()

### Store config
Please paste your config below.
```js
store = createStore(
  rootReducer,
  initState,
  compose(offline(reduxOfflineConf), applyMiddleware(createLogger())
)
```

where in reduxOfflineConf I am trying to do:

```js
{
  ...config,
  persist: false
}
```

This should be supported according to the docs, [here](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#persist):

> You can, however, pass a falsey value to prevent the state from being persisted.

But the typing seems to only accept:

```js
persist: (store: any, options: {}, callback: () => void) => any
```

Is this a bug or am I missing something?

**Comment by sorodrigo** [comment]
Yeah seems to me like the types are outdated. Thanks for pointing this out.

**Comment by sobrinho** [comment]
Types are broken, I will be working on this very soon but for now just disable the linter for the line.
