### ISSUE TITLE
Retry does not accept null

### ISSUE THREAD

**Issue by AnderssonChristian** [jevakallio/redux-offline#434]
### Are you using `offline()` or `createOffline()` API?
offline()

### Store config
Please paste your config below.
```js
store = createStore(
  rootReducer,
  initState,
  compose(offline(reduxOfflineConf), applyMiddleware(createLogger())
)
```

where in reduxOfflineConf I am trying to do:

```js
{
  ...config,
  retry: (_action, retries) => {
    const delays = [500, 1000, 2000];
    return retries < delays.length ? delays[retries] : null;
  }
}
```

This should be supported according to the docs, [here](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#retry):

>  or `null` if the action should be discarded

But the typing seems to only accept number or undefined:

```js
  retry: (action: OfflineAction, retries: number) => ?number,
```

Is this a bug or am I missing something?

**Comment by sorodrigo** [comment]
it should support null, I need to test this but doesn't the `?` mean that number can be null?

**Comment by AnderssonChristian** [comment]
@sorodrigo I don't think so. `?` means the value is optional/can be omitted. No value is `undefined` whereas `null` is an explicit value.

**Comment by sorodrigo** [comment]
could you try returning undefined?

**Comment by AnderssonChristian** [comment]
@sorodrigo I'll try it in a few. Though I suspect returning undefined will have the same effect as not specifying `retry` at all (default value/behavior).

**Comment by sorodrigo** [comment]
https://github.com/redux-offline/redux-offline/blob/develop/src/send.js#L93

Returning undefined will avoid retries.

**Comment by sobrinho** [comment]
Types are broken but returning either `undefined` or `null` will do the job.

I'm planning into working on the library types very soon and this will get fixed.

If the type checking is complaining, just skip the line, not ideal but does the job for now.
