### ISSUE TITLE
[Question]: how to deal with database auto numbers in offline mode

### ISSUE THREAD

**Issue by fhanggi** [jevakallio/redux-offline#437]
I'm new to react and offline. I have the following issue.
The backend DB generates auto numbers for the primary keys. I don't have that feature available offline so i'm generating a GUID and use that as the PK while offline.
In my custom effect i remove the GUID from the body and let the DB generate the auto number.

My problem is that this is ok for the POST but any subsequent PUT/PATCH/DELETE will fail because the GUID is now gone and doesn't exist in the backend.

What i think i have to do is that after the POST succeeds go and update all the PUT/PATCH/DELETE effects for the GUID with the new PK from the database.
Is that possible? If so any tips would be great.

### Are you using `offline()` or `createOffline()` API?
offline()

Here's my Store configuration including customizations

import { applyMiddleware, createStore } from "redux";
//composeWithDevTools replaces compose to make it easier to intergate the redux dev tools
import { composeWithDevTools } from "redux-devtools-extension";
import thunkMiddleware from "redux-thunk";
import rootReducer from "./reducers/Index";
import { ENABLE_PWA_OFFLINE } from "../lib/AppSettings";
import { offline } from "@redux-offline/redux-offline";
import defaultOfflineConfig from "@redux-offline/redux-offline/lib/defaults";
import * as localforage from "localforage";
import _ from "lodash";
import ApiService from "../lib/ApiService";

defaultOfflineConfig.persistOptions = { storage: localforage }; 

const customDiscard = async (error, _action, _retries) => {
  console.log("inside custom discard");
  console.log(error);
  console.log(_action);
  console.log(_retries);
  return error.status >= 400 && error.status < 500;
};

const customEffect = async (effect, action) => {
  const { url, body, headers, ...options } = effect;
  console.log("inside custom effect");
  console.log(action);
  console.log(effect);
  console.log(headers);
  console.log(body);
  console.log(url);
  console.log(options);

  //get a new header with and updated token
  // getHeader retrieves a  token from cache or gets a new token if the old one expired
  const newHeaders = await ApiService.getHeader();
  console.log(newHeaders);

  let bodyToSubmit = body;
  //custom code below for apps  that make use of identity keys
  //TODO set up a ap setting to control if this code should execute

  //check if this is a post and that the action type is "_ONLINE"
  //in this case we temporarily assinged a GUID to the id
  //we need to remove that GUID here so that the back end can generate the id
  if (
    action.meta.offline.commit.type.includes("_ONLINE") &&
    action.meta.offline.effect.method === "POST" &&
    bodyToSubmit !== null &&
    bodyToSubmit !== undefined &&
    bodyToSubmit.includes('"id":')
  ) {
    //find "id": and remove it
    //convert body into object so we can easily remove  id

    let newBody = JSON.parse(body);
    newBody = _.omit(newBody, ["id"]);
    bodyToSubmit = JSON.stringify(newBody);
  }

  let req;
  if (bodyToSubmit !== null && bodyToSubmit !== undefined) {
    console.log("submitting with body");
    console.log(bodyToSubmit);
    req = await fetch(url, { ...options, headers: newHeaders, body: bodyToSubmit });
  } else {
    console.log("submitting withOUT body");
    console.log(bodyToSubmit);
    req = await fetch(url, { ...options, headers: newHeaders });
  }

  //console.log(req);

  //data.catch()
  return req.json();
};

const customReduxOfflineConfig = {
  ...defaultOfflineConfig,
  discard: customDiscard,
  effect: customEffect
};

export default function configureStore(preloadedState) {
  const middlewares = [thunkMiddleware];
  const middlewareEnhancer = applyMiddleware(...middlewares);

  //compose the enhancers/middleware for our store
  let enhancers;
  if (ENABLE_PWA_OFFLINE().toLowerCase() === "true") {
    enhancers = [middlewareEnhancer, offline(customReduxOfflineConfig)];
    // enhancers = [middlewareEnhancer, offline(offlineConfig)];
  } else {
    enhancers = [middlewareEnhancer];
  }

  const composedEnhancers = composeWithDevTools(...enhancers);

  const store = createStore(rootReducer, preloadedState, composedEnhancers);

  return store;
}

### Are you reporting a bug?
no

**Comment by a3gz** [comment]
In these scenarios I like to maintain the GUID as a unique key in the database too.
My tables have the auto increment primary key and a GUID as a unique key. I use the auto increment for relations and back-end only processes but the front-end only sees GUIDs.

**Comment by fhanggi** [comment]
> In these scenarios I like to maintain the GUID as a unique key in the database too.
> My tables have the auto increment primary key and a GUID as a unique key. I use the auto increment for relations and back-end only processes but the front-end only sees GUIDs.

Thank you for the reply. Unfortunately I'm accessing a vendor db and cannot add GUID to their tables.

**Comment by williamgurzoni** [comment]
Hi @fhanggi I'm having a very similar issue. My solution at the moment is:

Using a custom `queue` function to filter my actions by `key`.
On the app side I check if I have a `id` for the object, if I don't have and I'm trying to `update`, I dispatch a `create` instead with the same `key`. (In my case `key` is a temporary id by process).

This way, I'll always have just one item (create/post) on the Outbox until the app get connected.

Limitation: Because I'm discarding the previous requests, I always have to send the full object to `create`.

**Comment by fhanggi** [comment]
I managed to find a solution. 

Inside a custom dequeue I detect if the item's meta contains a generated GUID . This way I know that i am dealing with a successful POST which contains the newly generated ID from the db inside the item's payload. I know it's a post because the POST will always be the first item in the queue for any given item.

I then loop through the outbox and update any matching GUID I find with the newly generated id.  See my dequeue code below

`  dequeue(array, item, context) {
    //dequeue is called after an item in the queue was successfully processed
    if (
      typeof item.meta.GUID !== "undefined" &&
      item.meta.GUID &&
      item.meta.success &&
      item.meta.completed
    ) {
      //now loop through the outbox and update any existing rows that match the GUID with the new id
      //then return the new outbox
      var i = 0,
        len = array.length;
      while (i < len) {
        //find any edits that were made using a GUID and replace the GUIUD with new id from DB
        if (array[i].type.includes("EDIT_")) {
          if (array[i].meta.offline.commit.meta.formValues.id === item.meta.GUID) {
            array[i].meta.offline.commit.meta.formValues.id = item.payload.id;
            //change body
            let newBody = JSON.parse(array[i].meta.offline.effect.body);
            newBody.id = item.payload.id;
            array[i].meta.offline.effect.body = JSON.stringify(newBody);
            //change url
            let newUrl = array[i].meta.offline.effect.url;
            //remove everything after the slash in the url
            newUrl = newUrl.substr(0, newUrl.lastIndexOf("/") + 1);
            //append new id to url
            newUrl = newUrl + item.payload.id;
            array[i].meta.offline.effect.url = newUrl;
          }
        }
        // find any deletes that were made offline using a GUID, replace GUID with new id from DB
        if (array[i].type.includes("DELETE_")) {
          //change form values
          if (array[i].payload.id === item.meta.GUID) {
            array[i].payload.id = item.payload.id;
            //change url
            let newUrl = array[i].meta.offline.effect.url;
            //remove everything after that slash
            newUrl = newUrl.substr(0, newUrl.lastIndexOf("/") + 1);
            newUrl = newUrl + item.payload.id;
            array[i].meta.offline.effect.url = newUrl;
          }
        }

        // find any fetches that were made offline using a GUID, replace GUID with new id from DB
        if (array[i].type.includes("FETCH_")) {
          if (array[i].payload && array[i].payload === item.meta.GUID) {
            array[i].payload = item.payload.id;
            //change url
            let newUrl = array[i].meta.offline.effect.url;
            //remove everything after the slash in the url
            newUrl = newUrl.substr(0, newUrl.lastIndexOf("/") + 1);
            //append new id to url
            newUrl = newUrl + item.payload.id;
            array[i].meta.offline.effect.url = newUrl;
          }
        }

        i++;
      }
    }

    //return new outbox
    const [, ...rest] = array;
    return rest;
  },
`

**Comment by timstallmann** [comment]
Just a note here that I'm also using @williamgurzoni's approach and it's working well -- also filtering the outbox so that if you create and then delete an object, all while offline, nothing ends up getting sent to the server at all.

Was worried that the approach @fhanggi proposes could break if there's a race condition (although maybe redux-offline guarantees that outbox actions will run in order?).

**Comment by fhanggi** [comment]
> Just a note here that I'm also using @williamgurzoni's approach and it's working well -- also filtering the outbox so that if you create and then delete an object, all while offline, nothing ends up getting sent to the server at all.
> 
> Was worried that the approach @fhanggi proposes could break if there's a race condition (although maybe redux-offline guarantees that outbox actions will run in order?).

Based on my tests redux-offline processes outbox actions in order.
So if a user creates a new entry offline and also deletes it offline then there's a POST and DELETE made after the user goes online. Kind of  a waste. 

I  think @williamgurzoni solution seems better but i am not quite sure how to implement it. @williamgurzoni would you mind sharing your custom enqueue with the filter?

**Comment by timstallmann** [comment]
Here's an example snippet from the way we're doing it; which has different cases based on the action type; it would probably be better to do something more generic but that would require refactoring all the site actions to have consistent payload structure, which I'm saving for another day 😄 

```js
export const enqueue = (array, action) => {
  const outbox = array;
  const { type, payload } = action;

  // Clear out any previous ADD_ITEM actions relating to the same camp/note, if any exist.
  if (type === ADD_ITEM.BASE) {
    return [
      ...outbox.filter(
        (a) => a.type !== ADD_ITEM.BASE || a.payload.uuid !== payload.uuid,
      ),
      action,
    ];
  }
... other cases here
return [...outbox, action];
```

**Comment by fhanggi** [comment]
@timstallmann  Thank you for the example . I'll try this out

**Comment by sobrinho** [comment]
The outbox is processed in order, in the case one request fails, it will retry until it succeeds or discards and then process the next item.

Now, for the problem itself, there's no standard way of doing it and a few examples are already mentioned, there's no silver bullet but I would follow that order:

1. Add support to UUID if possible
2. If not possible, i.e.: 3rd party vendors, use one of the mentioned solutions
3. Alternatively, you could proxy the requests to a micro-service which would save and translate the UUIDs before submitting to the actual 3rd service/vendor
