### ISSUE TITLE
Network errors (such as no server listening) not retried anymore?

### ISSUE THREAD

**Issue by tdd** [jevakallio/redux-offline#438]
### Are you using `offline()` or `createOffline()` API?

Using `offline()`

### Store config
```js
createStore(reducer, initialState, compose(offline(reduxOfflineConfig), devToolsEnhancer))
```

### Offline config

```js
const reduxOfflineConfig = {
  ...offlineConfig,
  persistOptions: {
    storage: localForage,
  },
}
```

### Are you reporting a bug?

It used to be that lack of a listening server was handled as a network error, and trigger retries just like 5xx HTTP responses.

Some time in the recent past, it started just triggering rollbacks instead, no retries get scheduled.

This isn't so great, and also makes it a bit harder to demonstrate retries during Redux training courses (which used to just require stopping the demo API server).

Is this intentional? Or is the `'status' in error` test in the default `discard()` not adequate anymore? Perhaps network errors in Chromium now feature a `status` property?

**Comment by sorodrigo** [comment]
Hello, sorry for answering just now, we haven't updated the logic behind it so it definitely sounds like a change in the error properties. Do you think you could override the default discard to solve this issue?

**Comment by tdd** [comment]
Hey @sorodrigo,

it ended up being a different issue. I had switched from a same-origin request to a CORS request, triggering CORS logic in the browser. Failed connectivity (no server running) meant failed pre-flight, which triggers a different kind of error than regular network errors, so the test in the default `discard()` doesn't match.

I could solve this in two ways, either using CRA's access to Webpack-Dev-Server's proxy feature to hop back on same-origin, or tweaking my demo server to toggle intentional 5xx responses. I chose the latter, which provides easier control during the training.

However, I think it would be neat if Redux-Offline's default `discard()` identified both network errors and CORS errors (which are very much network-related).

Best,

**Comment by sorodrigo** [comment]
> However, I think it would be neat if Redux-Offline's default discard() identified both network errors and CORS errors (which are very much network-related).

I understand but the defaults are designed to be as lean a possible. I'm not sure if they should worry of edge cases, besides CORS error means that it's a request error so the client shouldn't be retrying them. WDYT?

I prefer people composing the defaults with a custom fn that handles each edge case.

**Comment by tdd** [comment]
Hey!

I get the things about lean defaults. As for whether CORS is purely client- or network-related, I'm sure that's very much a personal perception thing :)

I would perhaps advocate the default discard/retry/accept behaviors be better documented (2xx, 4xx, 5xx, CORS, and perhaps a word on 3xx?) to reduce friction (at least for ppl who do read the docs 😉)

**Comment by sorodrigo** [comment]
Sounds good, since you now have a lot of context on this would you help me with a PR?

**Comment by tdd** [comment]
Yes I could; kinda overwhelmed with my daily work this week but let me slap a reminder on my calendar for next week so I can submit something.

**Comment by sobrinho** [comment]
I'm closing this since it's stale but feel free to open a PR improving this, it would be appreciated.
