### ISSUE TITLE
2.6.0-native.1 incorrect imports

### ISSUE THREAD

**Issue by mnightingale** [jevakallio/redux-offline#443]
Related #436

`yarn add @redux-offline/redux-offline@native`

The compiled lib tries to import NetInfo and AsyncStorage from react-native.

**Comment by sorodrigo** [comment]
Are you sure? Perhaps you need to remove the yarn.lock to get the latest version?

**Comment by sorodrigo** [comment]
This is the code I get:
```
var _asyncStorage = _interopRequireDefault(require("@react-native-async-storage/async-storage"));

var _netinfo = _interopRequireDefault(require("@react-native-community/netinfo"));
```

**Comment by mnightingale** [comment]
Apologies `yarn cache clear` seems to have sorted it.
Noticed lock file it was resolving to a really old release URL.
