### ISSUE TITLE
[Question]: Force Retry

### ISSUE THREAD

**Issue by williamgurzoni** [jevakallio/redux-offline#455]
### Are you using `offline()` or `createOffline()` API?
offline()

### Question
I have a scenario where I'd like to have a button for the user to "retry" a failed query.
Is it possible?

Thank you.

**Comment by sorodrigo** [comment]
hey, so this can be handled as a separate request. The flow would be like this:

1. Make request => 2. Request failed and triggered rollback => 3. rollback updates UI to show retry button => 4. onClick go to 1.

**Comment by williamgurzoni** [comment]
Thank you @sorodrigo 

I actually figure it out by dispatching the `OFFLINE_SCHEDULE_RETRY` action when the user tap `Retry`.

Documenting how I did for future searches:

```
import { OFFLINE_SCHEDULE_RETRY } from '@redux-offline/redux-offline/src/constants';

const retry = (delay = 100) => ({
  type: OFFLINE_SCHEDULE_RETRY,
  payload: {
    delay,
  },
});

// Action onPress retry button:
store.dispatch(retry);
```

Thank you.
