### ISSUE TITLE
Add data first in redux-persist and then call api in background 

### ISSUE THREAD

**Issue by Akashdeep312** [jevakallio/redux-offline#456]
Hi would like to know can we design this flow with redux-offline 

1.Add Data first to redux-persist .
2.Call the api if online.
3.Or wait till network status changes to online

**Comment by sorodrigo** [comment]
You can add the data in a reducer and this will be automatically persisted. Whats your use case?

**Comment by Akashdeep312** [comment]
Actually i want to add data first in our local storage and then if network is available make the request in background and if network not available then save the request in the queue to send when online

**Comment by sorodrigo** [comment]
yeah but why do you need the data in storage? If you have it in a reducer it will be persisted by redux-persist already.

**Comment by Akashdeep312** [comment]
Actually when we are online then our effect action is executed and if it is completed successfully then  we commit otherwise rollback, but i want to persist data first and then if our effect action succeed then add returned id to the item persisted else show the error and rollback . 
In my case i want data to be persisted before network call and after effect action is succeeded the id is synced to saved item .

**Comment by sorodrigo** [comment]
You should be able to do that by saving the data in a parallel reducer. SO when you dispatch a request, this reducer adds the request data to it's state and when commit happens, this reducer updates the related item.

**Comment by Akashdeep312** [comment]
Thanks @sorodrigo  for the suggestion I'll try to implement that in this weekend and get back to you  , for the time being I'm closing it
