### ISSUE TITLE
commit rollback are not being  called 

### ISSUE THREAD

**Issue by Akashdeep312** [jevakallio/redux-offline#458]
### Are you using `offline()` or `createOffline()` API?
_using createOffline()_

### Store config
Please paste your config below.
```js
import { createStore, applyMiddleware, compose } from "redux";
import { persistStore, persistReducer } from "redux-persist";
import AsyncStorage from "@react-native-async-storage/async-storage";
import ReduxThunk from "redux-thunk";
import ReduxLogger from "redux-logger";
import hardSet from "redux-persist/lib/stateReconciler/hardSet";
import rootReducer from "@store/store";

//offline
import { offline, createOffline } from "@redux-offline/redux-offline";
import offlineConfig from "@redux-offline/redux-offline/lib/defaults";

const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore
} = createOffline({
  ...offlineConfig,
  persist: false
});

const persistConfig = {
  key: "root",
  storage: AsyncStorage,
  stateReconciler: hardSet,
  whitelist: ["user", "inbox","app","offline"]
};


const persistedReducer = persistReducer(persistConfig, offlineEnhanceReducer(rootReducer));

const isDevMode = Boolean(__DEV__);

const middleWares = isDevMode ? [ReduxThunk,ReduxLogger] : [ReduxThunk];
const store = createStore(persistedReducer, {}, compose(offlineEnhanceStore, applyMiddleware(...middleWares)));

const persistor = persistStore(store);

export default { store, persistor };

```

### Action i'm using

```js
import { inboxActionTypes } from "@constants/action-types";

import { inbox } from "@constants/api-config";

const { fetchInboxItems, fetchInboxCommit, fetchInboxRollBack } = inboxActionTypes;

const InboxActions = {
  fetchInbox: token => dispatch =>
    dispatch({
      type: fetchInboxItems,
      meta: {
        offline: {
          effect: { url: inbox, method: "GET", headers: { Authorization: `JWT ${token}` } },
          commit: { type: fetchInboxCommit },
          rollback: { type: fetchInboxRollBack }
        }
      }
    })
};



export const { fetchInbox } = InboxActions;


```
_chrome screenshot_
### as you can see i'm not able to find any logs for commit or rollback

![Screen Shot 2021-07-21 at 2 00 31 PM](https://user-images.githubusercontent.com/48234644/126457679-f411b821-78d8-4f9c-b4a3-9bb9e6f6e83b.png)
If you need code indentation, you can use [Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fPz8Aeiz8ABVbABFbJHxC6AV9Gzh8akMoOggAW394tganDN19RJa+C0MYIQA6VHIafAYBoeG6huaGDwAqfABGAFEAagB2N2GYCABlGGpw5kXZuAAHEkMwOAYs-n5h57pNrJxmSUFBN3T4rUOLF4gAeOg4ez4MC3TSaAByhiacB4CmIZEoNHoCnwuBguh4wAABgBNaz4QxsfD2HDaA7UBLoJoAIyc+AAJMBGS0XESXPhLNY7I5qITBdUHE4XAA+AGZfCgzQnaDMaVc0KcZjDTQkHD3Bj4AAMklW+D2BwAqlcrk4AMKGUyLfCbKRsMJcbW6-Wrc0QAAyEAA7naHQ8PC5QVkldQVbLAX4WG7NcMEHRNBQcEMGBI-vgAPwCECF-ClRVXer4JUATwJwGAkHI1FKSn40irChcMokhcjmnLUGl+BcGT8oLgTTj-Bg6qTcDkw58MEj47j8q5DG0ulg-3jmQLgleIBHmVKgiCggXx8jEPs0rSPigLhA4hAECuuGgmmQoEpMcDAAVKQQL8UEMewIBwOhnxAZk6jAABrDhDnLMAzmQE50DMEBwlMagYH-OpmCaQxkCMEwsIAK00AAPAAhODEJgQ4kTgP1wjgUjjFMF9y2oXDkBgwxmRraBoKuU5YAzOghmQAAOY0QHEiBTAoOorgE8S4FwxxoLYABHdAcDYAjDCIkikDI7iQFMJocHQ6hMJfbQuF0ABFdAIHgezHJAGAhKkmSkAAJhfE5DB0M5bWaYiBKgaAOJfao8iEkDLLgTsgA).

### Are you reporting a bug?
IDK if it's a bug or some configuration issue from my end 

```js
  {
"react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.9",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "@redux-offline/redux-offline": "^2.6.0-native.1"
}
```

**Comment by sorodrigo** [comment]
It seems to me like you forgot to add `offlineMiddleware` to your middleware list.

**Comment by sobrinho** [comment]
@sorodrigo this can be closed.
