### ISSUE TITLE
Issues with installation due to AsyncStorage and NetInfo on 2.6.0-native.1

### ISSUE THREAD

**Issue by glowychan** [jevakallio/redux-offline#468]
Hello, I am having trouble installing the latest package version 2.6.0-native.1. I ran into two separate issues, and when I resolve one, the other will come up. Apologies if this is a duplicate issue, I was not sure as the similar posts I looked into seemed to be resolved.

1. At first I ran `yarn add @redux-offline/redux-offline@native` and had this error: `Unable to resolve module @react-native-async-storage/async-storage`. As [this post](https://github.com/redux-offline/redux-offline/issues/443#issuecomment-829279916) suggested, I had to delete the yarn.lock file and reinstall it.
2. After I got past the async storage error, I had `NetInfo has been removed from React Native error`. As [this post](https://github.com/redux-offline/redux-offline/issues/459) suggested, I removed the package and yarn.lock again, then I installed the exact version of the package via `yarn add -E @redux-offline/redux-offline@2.6.0-native.1`. But I will end up getting issue 1 again.

**Comment by sorodrigo** [comment]
do you have `@react-native-async-storage/async-storage` installed?

**Comment by glowychan** [comment]
Ah sorry, that was my bad - I did not realize my AsyncStorage was deprecated and updating it fixed this issue.
