### ISSUE TITLE
[Question] Where is the documentation?

### ISSUE THREAD

**Issue by charlestbell** [jevakallio/redux-offline#482]
I tried the link in the readme that is supposed to go to the documentation.
"See [Documentation](https://github.com/redux-offline/redux-offline/blob/develop/docs/README.md) for configuration options, the full API, and common recipes."

  only leads to a very minimal other readme with almost no content:
![redux-offline_README md at develop · redux-offline_redux-offline - Google Chrome 11_2_2021 12_56_39 PM](https://user-images.githubusercontent.com/54514092/139911071-6a504ac7-b4a9-4ed3-ad10-536a9ff51b11.jpg)

I tried googling it to no avail. 

Am I  missing something, or is there no documentation aside from the Quick Start?

**Comment by sorodrigo** [comment]
Thanks a lot for reporting. The new docs are here https://redux-offline.github.io/redux-offline/. I'll fix the link!!

**Comment by charlestbell** [comment]
Thanks!
