### ISSUE TITLE
[Feature request] Clear offline queue

### ISSUE THREAD

**Issue by jaydotcom** [jevakallio/redux-offline#502]
Hi there,
I was using this wonderful library for my next React Native app.
I was wondering how I can clear the queue (need it when user log out for example).
I didn't find this functionality anywhere.
Can you help me regarding this ?
Regards

**Comment by drsag-mgr** [comment]
Hi there, 
is there a solution in the meantime? I have the same problem.
Regards

**Comment by sobrinho** [comment]
You can dispatch `RESET_STATE` to clear everything out.

```ts
import { RESET_STATE } from "@redux-offline/redux-offline/lib/constants";

dispatch({ type: RESET_STATE });
```
