### ISSUE TITLE
How to dispatch an action from redux-offline dequeue function

### ISSUE THREAD

**Issue by zed-em** [jevakallio/redux-offline#507]
Scenario:

Go Offline:
Make 3 contacts t0, t1 and t2.
Update t1 to “t1 update”.
Make some transactions in t0 and “t1 update”.
Go online.

Result:
3 contacts created t0, t1 and t2 works as expected means their server_id and client_id are synced.
Update call ( t1 to “t1 update”) did not work well because at the time of this call t1 was not even created on server so there’s no id available and we are using [redux-offline](https://github.com/redux-offline/redux-offline) which stores the action with the payload provided to dispatch once connection restored so it dispatches update call with id null. 
Same case with transaction call because to make a transaction we need to send contact id which is not even present on server

Action look like this:
static addBusinesses(payload: any) {
		const { id, name = '', businessTypeId, clientId } = payload;
		const headers = handers.customHeaders();
		const body = {
			clientId,
			name,
			...(businessTypeId && { businessTypeId }),
			isSelected: true,
		};
		return {
			type: AccountTypes.ADD_BUSINESSES,
			payload,
			meta: {
				offline: {
					effect: {
						url: End_Points.BUSINESSES(id),
						method: Variable.METHOD.POST,
						json: body,
						headers,
					},
					commit: { type: AccountTypes.ADD_BUSINESSES_COMMIT },
					rollback: { type: AccountTypes.ADD_BUSINESSES_ROLLBACK },
				},
			},
		};
	}

root reducer is:

//Import: Dependencies
import { createStore, applyMiddleware, compose } from 'redux';
import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';
import defaultQueue from '@redux-offline/redux-offline/lib/defaults/queue';
import createSagaMiddleware from 'redux-saga';
import { ApiCaller, customConfig } from '../services';
import asyncDispatchMiddleware from '../middleware/asyncDispatch';
// Imports: Redux Root Reducer
import rootReducer from './reducers/index';

// Imports: Redux Root Saga
import { rootSaga } from './saga';

// Middleware: Redux logger
import logger from 'redux-logger';

// Middleware: Redux Saga
const sagaMiddleware = createSagaMiddleware();

// Redux: Store
//const store = offline(offlineConfig)(createStore)(
const store = offline(customConfig)(createStore)(
	rootReducer,
	{ ...rootReducer },
	_getMiddlewares(),
);

function _getMiddlewares() {
	//let middlewares = [asyncDispatchMiddleware, sagaMiddleware];
	let middlewares = [sagaMiddleware];
	return applyMiddleware(...middlewares);
}

// Middleware: Redux Saga
sagaMiddleware.run(rootSaga);

// Exports
export { store };

Here is cutomConfig

const customConfig = {
	queue: {
		...defaultQueue,
		dequeue(array, action, context) {
			
			for (let i = 0; i < array.length; i++) {
				const { payload, type } = array[i];
				if (payload?.serverId == null) {
					 store.dispatch({
					 	type,
					 	payload,
					 });
					
				}
				
			}
			array.shift();
			return array;
		},
	},
};

I'm making offline first application and I want to swap local_id with server_id before making api call, so I want to check payload if the serverId is null then I want to dispatch the action again.

When I try to dispatch action in dequeue function I got this error **Error: Reducers may not dispatch actions.**

**Comment by sobrinho** [comment]
What you need to do here is keep track of the not-yet-saved items on memory with something like an UUID.

There are a few solutions on https://github.com/redux-offline/redux-offline/issues/437
