### ISSUE TITLE
How to have a history of outbox

### ISSUE THREAD

**Issue by saeedtkh** [jevakallio/redux-offline#514]
Is there any way to have a history from the outbox? because each time we connect to internet the outbox become empty as it should be. But we can not track the apis that are executed. Any idea?

**Comment by sobrinho** [comment]
I never done it myself but I would try to inject into the `dequeue` config: https://redux-offline.github.io/redux-offline/docs/api/config/#queuedequeue

Didn't try but:

```js
import { createStore } from 'redux';
import { offline } from '@redux-offline/redux-offline';
import defaultConfig from '@redux-offline/redux-offline/lib/defaults';

const config = {
  ...defaultConfig,

  dequeue: (array, item, context) {
    recordCalledItem(item); // do what you need to do here

    return defaultConfig.dequeue(array, item, context);
  }
}

const store = createStore(myReducer, offline(config));
```

Or even in the `effect` before dispatching, you could dispatch an action to keep a history:

```js
const config = {
  ...defaultConfig,

  effect: (effect, action) => {
    const response = axios(effect);

    response.then(response => {
      recordAxiosCall(response);
      return response;
    }

    return response;
  }
}
```

You could also try in the store itself by listening to the actions here: https://github.com/redux-offline/redux-offline/blob/2308c02693876d3430d22a283e55ecda8351a96a/src/updater.js#L89-L112

You can also do this back-end wise by creating logs there if you control the back-end.

Feel free to suggest or post alternative solutions here.
