### ISSUE TITLE
Error: undefined Unable to resolve module @redux-offline/redux-offline

### ISSUE THREAD

**Issue by muhamedoufi** [jevakallio/redux-offline#520]
unable to resolve native version in react native 0.68.2
my package.json
 `"dependencies": {
    "@react-native-community/netinfo": "^9.3.0",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@redux-devtools/extension": "^3.2.2",
    "@redux-offline/redux-offline": "^2.6.0-native.1",
    "@reduxjs/toolkit": "^1.8.3",
    "axios": "^0.27.2",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-action-button": "^2.8.5",
    "react-native-offline": "^6.0.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-redux": "^8.0.2",
    "redux-persist": "^6.0.0",
    "redux-persist-sqlite-storage": "^1.0.4",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.4.1"
  },`

**Comment by sobrinho** [comment]
@sorodrigo this is stale, you can close it out.
