### ISSUE TITLE
Please fix imports

### ISSUE THREAD

**Issue by daimonkor** [jevakallio/redux-offline#524]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@redux-offline/redux-offline@2.6.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@redux-offline/redux-offline/src/defaults/detectNetwork.native.js b/node_modules/@redux-offline/redux-offline/src/defaults/detectNetwork.native.js
index 65bcfb2..d366fba 100644
--- a/node_modules/@redux-offline/redux-offline/src/defaults/detectNetwork.native.js
+++ b/node_modules/@redux-offline/redux-offline/src/defaults/detectNetwork.native.js
@@ -1,5 +1,6 @@
 /* eslint no-underscore-dangle: 0 */
-import { AppState, NetInfo } from 'react-native'; // eslint-disable-line
+import { AppState } from 'react-native';
+import NetInfo from '@react-native-community/netinfo';// eslint-disable-line
 import LegacyDetectNetwork from './detectNetwork.native.legacy';
 
 class DetectNetwork {
diff --git a/node_modules/@redux-offline/redux-offline/src/defaults/persist.native.js b/node_modules/@redux-offline/redux-offline/src/defaults/persist.native.js
index c92704a..6de9d8f 100644
--- a/node_modules/@redux-offline/redux-offline/src/defaults/persist.native.js
+++ b/node_modules/@redux-offline/redux-offline/src/defaults/persist.native.js
@@ -1,6 +1,6 @@
 // @flow
 // $FlowIgnore
-import { AsyncStorage } from 'react-native'; // eslint-disable-line
+import AsyncStorage from '@react-native-async-storage/async-storage';
 import { persistStore } from 'redux-persist';
 
 export default (store: any, options: {}, callback: any) =>
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by DavidPurcell1973** [comment]
Did this fix actually work? my app is showing offline permanently offline using this solution.

**Comment by sorodrigo** [comment]
Have you tried using the `@native` tag? These changes should be there already https://github.com/redux-offline/redux-offline#for-react-native-060

I will try to release a new version this weekend that includes this breaking changes. It's been a while since this changed, no need to be backwards compatible friendly anymore.

**Comment by DavidPurcell1973** [comment]
Installing with the native tag works!! thanks for that. very much appreciate your work
