### ISSUE TITLE
🚨🚨🚨🚨 Maintainers wanted

### ISSUE THREAD

**Issue by sorodrigo** [jevakallio/redux-offline#525]
For the good of this community, I'm looking for a maintainer that uses this tool in a regular basis (I no longer do) and that's willing to update/maintain and revamp.

**Comment by mateusschenato** [comment]
Hello,

I've using redux-offline a lot. Please contact me, i'm interested to mantain project

**Comment by sorodrigo** [comment]
@mateusschenato I emailed you!

**Comment by carlosbensant** [comment]
A few years ago, this library helped to build an offline-first application and I would like to know what alternatives there are out there to achieve the same as it seems this one to be abandoned.

**Comment by preppygassou** [comment]
> For the good of this community, I'm looking for a maintainer that uses this tool in a regular basis (I no longer do) and that's willing to update/maintain and revamp.

I want to continue maintain

**Comment by LucasHang** [comment]
Also willing to contribute. Just opened an issue about a new feature that I could implement.

**Comment by sorodrigo** [comment]
After the hack that happened to `xc` I'm not super comfortable giving away the library to someone I don't know. So what I can do is recommend users to download a fork instead. If you want this project to continue it's life please fork the repo.

**Comment by piranna** [comment]
Wouldn't It be easier to merge and publish the actual PRs, and later left It in maintenance mode? You would only need to review and aprove PRs, no need to be actively developing It...

**Comment by LucasHang** [comment]
> Wouldn't It be easier to merge and publish the actual PRs, and later left It in maintenance mode? You would only need to review and aprove PRs, no need to be actively developing It...

"only" would be a huge understatement of the real work of review, answering and merging all the PRs. But surely would be extremely apreciated.
@sorodrigo, if you will consider the suggestion of @piranna, you could make a list of the main PRs you judge worthy of review and put them here. This way, we can help you review those specific PRs and give some feedback or point improving/fixing changes.

**Comment by sorodrigo** [comment]
@piranna you're a long time contributor to this project, you've been here since the very beginning. Wanna take the lead?

**Comment by sorodrigo** [comment]
@LucasHang I can review and make a version with the latest PRs. But I think it's not that simple cause at some point we started distributing different versions depending on whether the RN version was x or y and whether the users where using expo or not.

What would be super helpful is for someone to go through the versions and the open PRs. And share a path forward.

Ex.

1. Merge PR # 123
2. Discontinue expo version (not needed anymore since x)
3. bump dependencies to x.y.z

etc.

If we have a plan like that, then I can jump in and do the required changes.

**Comment by LucasHang** [comment]
@sorodrigo I'd like to help, but I'm not sure I understand what you mean. Maybe by PRs you also mean Issues, that would make sense for me.
But anyway I'm not sure of what I must do in practice.

Let me explain to you what I know of the lib and what I think you mean, than you can correct me:

- The project has 3 main versions (native 0.60 or newer, expo sdk 36 or newer, default)
- There is a v3 partially implemented (do you think it should be finished?)

On this context, some Issues and PRs can point to different distributions and you would like to someone identify it and comment in the Issue/PR?
There is also the chance that the given Issue is resolved by a pending PR/bump, and you would like as well that someone points it out?

**Comment by piranna** [comment]
> @piranna you're a long time contributor to this project, you've been here since the very beginning. Wanna take the lead?

I have not been using this dependency since almost 5 years ago, but definitely I'm interested on my PRs to get merged in case I need to use it again. I could be able to review PRs and participate on discussions, but right now I'm not able to dedicate time to develop it myself.

**Comment by sobrinho** [comment]
I started closing some issues and I will work on some PRs as well for now.

If anyone is interested in helping, feel free to ping me on the issues and PRs.
