### ISSUE TITLE
How to handle array buffer response while using method is "GET"  

### ISSUE THREAD

**Issue by paddu1246** [jevakallio/redux-offline#527]
meta:{
            offline:{
                effect:{
                    url:`${baseUrl}/document/download/1920`,
                    method: 'GET',
                    headers: {
                        'responseType': 'arraybuffer',
                        'Authorization': token,
                    }
                },
                commit: {
                    type: AppConstants.ADD_OR_REMOVE_DOWNLOADSTATUS_MDOC_RECORDS,
                    meta:mDocMetaData,
                    payload: "",
                    pakki:"success"
                },
                rollback: {
                    type: AppConstants.ADD_OR_REMOVE_DOWNLOADSTATUS_MDOC_RECORDS,
                    pakki:"fail",
                    payload: "",
                    meta:mDocMetaData,
                }
            }
        } 

Here response. data is an array buffer for file downloading 

I am getting an error, like I Unexpected token '%', in the payload
![image](https://user-images.githubusercontent.com/37340127/203924249-92192e25-832e-455f-a8f2-37c060248807.png)

**Comment by paddu1246** [comment]
Please help me with this issue

**Comment by sobrinho** [comment]
Closing since it's stale but looks like you are getting a PDF response and trying to parse it as JSON.

You can configure the `effect` option to deal with the content type properly.
