### ISSUE TITLE
I want to change the number of retry and retry interval. Can anyone help, how I can configure my store to do that.

### ISSUE THREAD

**Issue by nitesh047** [jevakallio/redux-offline#549]
This is my store for now.

import {createStore, applyMiddleware,compose} from 'redux';
import thunk from 'redux-thunk';
import {persistStore, persistReducer} from 'redux-persist';
import reducers from './reducers';
import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults'
import AsyncStorage from '@react-native-async-storage/async-storage';

n 
 export const store = createStore(
    reducers,{}, compose(applyMiddleware(thunk), offline(OfflineConfig) )
);

**Comment by sobrinho** [comment]
You can configure the retry option: https://redux-offline.github.io/redux-offline/docs/api/config#retry

The default implementation is here: https://github.com/redux-offline/redux-offline/blob/develop/src/defaults/retry.js

```js
import defaultOfflineConfig from '@redux-offline/redux-offline/lib/defaults'

const offlineConfig = {
  ...defaultOfflineConfig,

  // retry every 1 second until 5 retries and then gives up
  retry: (action, retries) => retries < 5 ? 1000 : null
}
```
